### ISSUE TITLE
Yeoman no detection

### ISSUE THREAD

**Issue by Lmendev** [gverschuur/generator-php-cli-app#1] opened 2015-10-15 21:23 UTC
This generator no works for me. When I run Yo command, Yeoman doesn't recognize it.

**Comment by kostajh** [comment] 2015-10-26 00:14
Same here.

**Comment by verschuur** [comment] 2015-11-05 19:14
My apologies, I completely missed this issue. I've been having the same error when using the NPM version, I'll get on it and keep you updated.

**Comment by verschuur** [comment] 2015-11-05 22:42
Fixed in ab4fe5ca00965be01a679dd74625602d3db5acd0. Please give it a try.

**Comment by verschuur** [comment] 2015-11-18 09:37
@kostajh, @lmendoza92, could you please update the generator and give it a try, see if the issue is fixed for you?

**Comment by kostajh** [comment] 2015-12-01 14:11
@gverschuur it works, but I get "Could not open input file" when I try to run the example command.

**Comment by verschuur** [comment] 2015-12-08 20:47
@kostajh When the generator has finished running and I run 

`php test` I get the response  `Test version 1.0` which is as expected. 

Is the PHP CLI command callable from the command line? And if so, can you give me some info about your setup? OS, PHP version, etc

**Comment by verschuur** [comment] 2016-12-13 21:02
Closed due to inactivity.

**Closed as completed by verschuur** 2016-12-13 21:02 UTC
